- hosts: news487
  become: True
  become_method: sudo

  vars:
    image_name: scrapper487
    module_name: scrapper487-collector

  roles:
    - common

  tasks:
    - name: Update image
      shell: docker pull andre487/{{ image_name }}

    - name: Stop container
      shell: |
        docker stop {{ module_name }} || true
        docker rm {{ module_name }} || true

    - name: Start container
      shell: |
        docker run \
          -d \
          --restart always \
          --network {{ network_name }} \
          --name {{ module_name }} \
          -e TWITTER_CONSUMER_KEY={{ lookup('file', '~/.private/TWITTER_SCRAPPER_487_CONSUMER_KEY') }} \
          -e TWITTER_CONSUMER_SECRET={{ lookup('file', '~/.private/TWITTER_SCRAPPER_487_CONSUMER_SECRET') }} \
          -e TWITTER_ACCESS_TOKEN_KEY={{ lookup('file', '~/.private/TWITTER_SCRAPPER_487_ACCESS_TOKEN_KEY') }} \
          -e TWITTER_ACCESS_TOKEN_SECRET={{ lookup('file', '~/.private/TWITTER_SCRAPPER_487_ACCESS_TOKEN_SECRET') }} \
          -e MAIL_SERVER={{ lookup('file', '~/.private/SUBSCRIBE_MAIL_SERVER') }} \
          -e MAIL_LOGIN={{ lookup('file', '~/.private/SUBSCRIBE_MAIL_LOGIN') }} \
          -e MAIL_PASSWORD={{ lookup('file', '~/.private/SUBSCRIBE_MAIL_PASSWORD') }} \
          -e MONGO_HOST={{ mongo_name }} \
          andre487/{{ image_name }} \
          bash -c '/usr/local/bin/app/.devtools/schedule run all'
