- hosts: all
  remote_user: '{{ remote_user }}'
  become: True
  become_method: sudo

  tasks:
    - name: Update image
      shell: docker pull andre487/scrapper487

    - name: Stop container
      shell: |
        container_res="$(docker ps | grep scrapper487-collector || true)"
        if [[ -n "$container_res" ]]; then
            docker stop scrapper487-collector
            docker rm scrapper487-collector
        fi

    - name: Restart container
      shell: |
        docker run \
          -d \
          --restart always \
          --link common-mongo \
          --name scrapper487-collector \
          -e 'TWITTER_CONSUMER_KEY={{ lookup('file', '~/.private/TWITTER_SCRAPPER_487_CONSUMER_KEY') }}' \
          -e 'TWITTER_CONSUMER_SECRET={{ lookup('file', '~/.private/TWITTER_SCRAPPER_487_CONSUMER_SECRET') }}' \
          -e 'TWITTER_ACCESS_TOKEN_KEY={{ lookup('file', '~/.private/TWITTER_SCRAPPER_487_ACCESS_TOKEN_KEY') }}' \
          -e 'TWITTER_ACCESS_TOKEN_SECRET={{ lookup('file', '~/.private/TWITTER_SCRAPPER_487_ACCESS_TOKEN_SECRET') }}' \
          -e 'MAIL_SERVER={{ lookup('file', '~/.private/SUBSCRIBE_MAIL_SERVER') }}' \
          -e 'MAIL_LOGIN={{ lookup('file', '~/.private/SUBSCRIBE_MAIL_LOGIN') }}' \
          -e 'MAIL_PASSWORD={{ lookup('file', '~/.private/SUBSCRIBE_MAIL_PASSWORD') }}' \
          -e MONGO_HOST=common-mongo \
          andre487/scrapper487 \
          bash -c '/usr/local/bin/app/.devtools/schedule run all'
