#!/usr/bin/env bash -e

dir=$(cd "$(dirname $0)" && pwd)

interval=3600
if [[ -n "$SCHEDULE_INTERVAL" ]]; then
    interval="$SCHEDULE_INTERVAL"
fi

while true; do
    "$dir/scrap.py" $@
    sleep "$interval"
done
