- hosts: all
  remote_user: '{{ remote_user }}'
  become: True
  become_method: sudo

  vars:
    module_name: '{{ api_name }}'
    service_host: '{{ scrapper_487_api_host }}'
    service_port: 10100

  roles:
    - common
    - nginx_ssl_host
    - prepare_install_container

  tasks:
    - name: Start container
      shell: |
        docker run \
          -d \
          --restart always \
          --network {{ network_name }} \
          --name {{ module_name }} \
          -e MONGO_HOST={{ mongo_name }} \
          -e SPHINX_HOST={{ sphinx_name }} \
          -e SCRAPPER_API_URL={{ lookup('file', '~/.private/SCRAPPER_487_API_URL') }} \
          -p 127.0.0.1:{{ service_port }}:5000 \
          andre487/{{ module_name }}
