- hosts: all
  become: True
  become_method: sudo

  vars:
    module_name: scrapper487-web-ui
    service_host: '{{ scrapper_487_web_ui_host }}'
    nginx_locations: "{{ lookup('template', 'templates/nginx-locations.conf.j2') }}"

  roles:
    - common
    - nginx_ssl_host

  tasks:
    - name: Copy build to server
      synchronize:
        src: ../build
        dest: /var/www/{{ scrapper_487_web_ui_host }}
        delete: True
