- hosts: news487
  become: True
  become_method: sudo

  vars:
    module_name: scrapper487-pusher
    service_host: '{{ scrapper_487_pusher_host }}'
    service_port: 10101

  roles:
    - common
    - nginx_ssl_host
    - prepare_install_container

  tasks:
    - name: Start container
      shell: |
        docker run \
          -d \
          --restart always \
          --network {{ network_name }} \
          --name {{ module_name }} \
          -e MONGO_HOST={{ mongo_name }} \
          -e FIREBASE_SERVER_KEY={{ lookup('file', '~/.private/SCRAPPER_487_FIREBASE_SERVER_KEY') }} \
          -p 127.0.0.1:{{ service_port }}:5001 \
          andre487/{{ module_name }}
