#!/usr/bin/env bash -e

CUR_DIR="$(cd "$(dirname "$0")" && pwd)"
source "${CUR_DIR}/_common"

docker run \
    --rm \
    --link dev-mongo \
    -ti \
    -e TWITTER_CONSUMER_KEY="$(cat ~/.private/TWITTER_SCRAPPER_487_CONSUMER_KEY)" \
    -e TWITTER_CONSUMER_SECRET="$(cat ~/.private/TWITTER_SCRAPPER_487_CONSUMER_SECRET)" \
    -e TWITTER_ACCESS_TOKEN_KEY="$(cat ~/.private/TWITTER_SCRAPPER_487_ACCESS_TOKEN_KEY)" \
    -e TWITTER_ACCESS_TOKEN_SECRET="$(cat ~/.private/TWITTER_SCRAPPER_487_ACCESS_TOKEN_SECRET)" \
    -e MAIL_SERVER="$(cat ~/.private/SUBSCRIBE_MAIL_SERVER)" \
    -e MAIL_LOGIN="$(cat ~/.private/SUBSCRIBE_MAIL_LOGIN)" \
    -e MAIL_PASSWORD="$(cat ~/.private/SUBSCRIBE_MAIL_PASSWORD)" \
    -e MAIL_READONLY=1 \
    "$REPO_NAME" \
    /usr/local/bin/app/scrap.py --mongo=dev-mongo run all
