#!/usr/bin/env bash

set -ex

dir="$(cd "$(dirname "$0")" && pwd)"

"$dir/../run-test"

"$dir/docker-build"

log_file="$(mktemp)"
"$dir/docker-test" | tee "$log_file"

set +ex
errors="$(grep ERROR "$log_file")"
set -ex

if [[ -n "$errors" ]]; then
    echo "$errors"
    exit 1
fi

"$dir/docker-push"

ansible-playbook -i ~/.private/home-server-inventory "$dir/update-on-server.yml"
