- hosts: all
  remote_user: '{{ remote_user }}'
  become: True
  become_method: sudo

  tasks:
    - name: Run on server
      shell: |
        docker run \
          -d \
          --restart always \
          --name scrapper487 \
          --link common-mongo \
          andre487/scrapper487 \
          /usr/local/bin/app/schedule --mongo common-mongo run all
