- hosts: all
  remote_user: '{{ remote_user }}'
  become: True
  become_method: sudo

  tasks:
    - name: Update image
      shell: docker pull andre487/scrapper487

    - name: Restart container
      shell: |
        docker stop scrapper487 && \
        docker rm scrapper487 && \
        docker run \
          -d \
          --restart always \
          --link common-mongo \
          --name scrapper487 \
          andre487/scrapper487 \
          /usr/local/bin/app/schedule --mongo common-mongo run all
