- hosts: all
  remote_user: '{{ remote_user }}'
  become: True
  become_method: sudo

  tasks:
    - name: Update image
      shell: docker pull andre487/scrapper487

    - name: Restart container
      shell: |
        docker stop scrapper487 && \
        docker rm scrapper487 && \
        docker run \
          -d \
          --restart always \
          --link common-mongo \
          --name scrapper487 \
          -e 'TWITTER_CONSUMER_KEY={{ lookup('file', '~/.private/TWITTER_SCRAPPER_487_CONSUMER_KEY') }}' \
          -e 'TWITTER_CONSUMER_SECRET={{ lookup('file', '~/.private/TWITTER_SCRAPPER_487_CONSUMER_SECRET') }}' \
          -e 'TWITTER_ACCESS_TOKEN_KEY={{ lookup('file', '~/.private/TWITTER_SCRAPPER_487_ACCESS_TOKEN_KEY') }}' \
          -e 'TWITTER_ACCESS_TOKEN_SECRET={{ lookup('file', '~/.private/TWITTER_SCRAPPER_487_ACCESS_TOKEN_SECRET') }}' \
          andre487/scrapper487 \
          /usr/local/bin/app/schedule --mongo common-mongo run all
