export const TOGGLE_MENU = 'TOGGLE_MENU';
export const SELECT_FILTER = 'SELECT_FILTER';

export const REQUEST_CATEGORIES = 'REQUEST_CATEGORIES';
export const RECEIVE_CATEGORIES = 'RECEIVE_CATEGORIES';

export const REQUEST_DOCS = 'REQUEST_DOCS';
export const RECEIVE_DOCS = 'RECEIVE_DOCS';
export const RECEIVE_DOCS_ERROR = 'RECEIVE_DOCS_ERROR';
export const ERASE_ERROR = 'ERASE_ERROR';

export const TEXT_SEARCH = 'TEXT_SEARCH';
export const TAG_SEARCH = 'TAG_SEARCH';

export const CHANGE_CARD_EXPAND = 'CHANGE_CARD_EXPAND';

export const SHOW_VIDEO = 'SHOW_VIDEO';
export const HIDE_VIDEO = 'HIDE_VIDEO';
