export const SYNC_ROUTES = 'SYNC_ROUTES';

export const TOGGLE_MENU = 'TOGGLE_MENU';
export const SELECT_FILTER = 'SELECT_FILTER';

export const REQUEST_CATEGORIES = 'REQUEST_CATEGORIES';
export const RECEIVE_CATEGORIES = 'RECEIVE_CATEGORIES';

export const REQUEST_DOCS = 'REQUEST_DOCS';
export const RECEIVE_DOCS = 'RECEIVE_DOCS';
