export const TOGGLE_MENU = 'TOGGLE_MENU';
export const REQUEST_CATEGORIES = 'REQUEST_CATEGORIES';
export const RECEIVE_CATEGORIES = 'RECEIVE_CATEGORIES';
export const SELECT_FILTER = 'SELECT_FILTER';
