- hosts: all
  become: True
  become_method: sudo

  vars:
    module_name: news-bot487

  roles:
    - common
    - prepare_install_container

  tasks:
    - name: Start container
      shell: |
        docker run \
          -d \
          --restart always \
          --network {{ network_name }} \
          --name {{ module_name }} \
          -e TELEGRAM_TOKEN={{ lookup('file', '~/.private/NEWS_487_TOKEN') }} \
          -e MONGO_HOST={{ mongo_name }} \
          -e GOO_GL_KEY={{ lookup('file', '~/.private/GOO_GL_KEY') }} \
          -e API_URL=http://{{ api_name }}:5000 \
          andre487/{{ module_name }}
