- hosts: all
  remote_user: '{{ remote_user }}'
  become: True
  become_method: sudo

  tasks:
    - name: Setup NGINX host config
      template:
        src: templates/nginx.conf.j2
        dest: /etc/nginx/sites-available/scrapper487-api.conf

    - name: Enable NGINX host
      file:
        src: /etc/nginx/sites-available/scrapper487-api.conf
        dest: /etc/nginx/sites-enabled/scrapper487-api.conf
        state: link

    - name: Restart NGINX
      service:
        name: nginx
        state: restarted

    - name: Run on server
      shell: |
        docker run \
          -d \
          --restart always \
          --name scrapper487-api \
          --link common-mongo \
          -e 'MONGO_HOST=common-mongo' \
          -e 'TWITTER_CONSUMER_KEY={{ lookup('file', '~/.private/TWITTER_CONSUMER_KEY') }}' \
          -e 'TWITTER_CONSUMER_SECRET={{ lookup('file', '~/.private/TWITTER_CONSUMER_SECRET') }}' \
          -e 'TWITTER_ACCESS_TOKEN_KEY={{ lookup('file', '~/.private/TWITTER_ACCESS_TOKEN_KEY') }}' \
          -e 'TWITTER_ACCESS_TOKEN_SECRET={{ lookup('file', '~/.private/TWITTER_ACCESS_TOKEN_SECRET') }}' \
          -p 127.0.0.1:10100:5000 \
          andre487/scrapper487-api
