- hosts: all
  remote_user: '{{ remote_user }}'
  become: True
  become_method: sudo

  tasks:
    - name: Update image
      shell: docker pull andre487/scrapper487-api

    - name: Restart container
      shell: |
        docker stop scrapper487-api && \
        docker rm scrapper487-api && \
        docker run \
          -d \
          --restart always \
          --link common-mongo \
          --name scrapper487-api \
          -e 'MONGO_HOST=common-mongo' \
          -e 'SCRAPPER_API_URL={{ lookup('file', '~/.private/SCRAPPER_487_API_URL') }}' \
          -p 127.0.0.1:10100:5000 \
          andre487/scrapper487-api
