- hosts: news487
  become: True
  become_method: sudo

  vars:
    module_name: '{{ sphinx_name }}'

  roles:
    - common
    - prepare_install_container

  tasks:
    - name: Run container
      shell: |
        docker run \
          -d \
          --restart always \
          --name {{ module_name }} \
          --network {{ network_name }} \
          -e MONGO_HOST={{ mongo_name }} \
          andre487/{{ module_name }}
