- hosts: all
  remote_user: '{{ remote_user }}'
  become: True
  become_method: sudo

  tasks:
    - name: Update image
      shell: docker pull andre487/scrapper487-sphinx

    - name: Stop container
      shell: |
        container_res="$(docker ps | grep scrapper487-sphinx || true)"
        if [[ -n "$container_res" ]]; then
            docker stop scrapper487-sphinx
            docker rm scrapper487-sphinx
        fi

    - name: Run container
      shell: |
        docker run \
          -d \
          --restart always \
          --name scrapper487-sphinx \
          --link common-mongo \
          -e MONGO_HOST=common-mongo \
          andre487/scrapper487-sphinx
