- hosts: all
  remote_user: '{{ remote_user }}'
  become: True
  become_method: sudo

  tasks:
    - name: Ensure MongoDB runs
      service: |
        name=mongod
        state=started

    - name: Update image
      shell: docker pull andre487/news-bot487

    - name: Restart container
      shell: |
        docker stop news-bot487 && \
        docker rm news-bot487 && \
        docker run \
          -d \
          --restart always \
          --link scrapper487-api \
          --link common-mongo \
          --name news-bot487 \
          -e 'TELEGRAM_TOKEN={{ lookup('file', '~/.private/NEWS_487_TOKEN') }}' \
          -e 'MONGO_HOST=common-mongo' \
          -e 'API_URL=http://scrapper487-api:5000' \
          andre487/news-bot487
