#!/usr/bin/env python
import mongo_db
import sys
import proj_constants as const

from xml.sax.saxutils import escape as xml_escape


def main():
    client = mongo_db.get_client()
    if not client:
        raise EnvironmentError('Unable to connect to MongoDB')

    cursor = client[const.NEWS_DB][const.NEWS_COLLECTION].find({})

    print (
        '<?xml version="1.0" encoding="utf-8"?>\n'
        '<sphinx:docset xmlns:sphinx="http://sphinxsearch.com/">'
    )

    for doc in cursor:
        doc_id = str(doc['_id'])
        sphinx_id = long(doc_id, 16) % sys.maxint

        title = (doc['title'] or '').encode('utf-8')
        description = (doc['description'] or '').encode('utf-8')
        orig_description = (doc.get('orig_description') or '').encode('utf-8')
        text = (doc.get('text') or '').encode('utf-8')

        print (
            '<sphinx:document id="{sphinx_id}">\n'
            '<doc_id>{doc_id}</doc_id>\n'
            '<title>{title}</title>\n'
            '<text>{text}</text>\n'
            '<description>{description}</description>\n'
            '<orig_description>{orig_description}</orig_description>\n'
            '</sphinx:document>'
        ).format(
            sphinx_id=sphinx_id,
            doc_id=doc_id,
            title=xml_escape(title),
            text=xml_escape(text),
            description=xml_escape(description),
            orig_description=xml_escape(orig_description),
        )

    print '</sphinx:docset>'

    client.close()


if __name__ == '__main__':
    main()
