#!/usr/bin/env python
import json
import os
import pymongo
import sys

from xml.sax.saxutils import escape as xml_escape

host = os.environ.get('MONGO_HOST')
port = int(os.environ.get('MONGO_PORT', 27017))

mongo_db = os.environ.get('MONGO_DB', 'news_documents')
mongo_collection = os.environ.get('MONGO_COLLECTION', 'items')

if not host:
    raise EnvironmentError('You should provide MONGO_HOST env var')


def main():
    try:
        with open('/var/log/sphinx/test.json', 'w') as f:
            json.dump(sys.argv, f)
    except:
        pass

    db = pymongo.MongoClient(host, port)[mongo_db]
    collection = db[mongo_collection]

    cursor = collection.find({})

    print (
        '<?xml version="1.0" encoding="utf-8"?>\n'
        '<sphinx:docset xmlns:sphinx="http://sphinxsearch.com/">'
    )

    for doc in cursor:
        doc_id = str(doc['_id'])
        sphinx_id = long(doc_id, 16) % sys.maxint

        title = (doc['title'] or '').encode('utf-8')
        description = (doc['description'] or '').encode('utf-8')
        text = (doc.get('text') or '').encode('utf-8')

        print (
            '<sphinx:document id="{sphinx_id}">\n'
            '<doc_id>{doc_id}</doc_id>\n'
            '<title>{title}</title>\n'
            '<text>{text}</text>\n'
            '<description>{description}</description>\n'
            '</sphinx:document>'
        ).format(
            sphinx_id=sphinx_id,
            doc_id=doc_id,
            title=xml_escape(title),
            text=xml_escape(text),
            description=xml_escape(description),
        )

    print '</sphinx:docset>'


if __name__ == '__main__':
    main()
