#!/usr/bin/env python
import logging_common
import data_provider

logging_common.setup()


def main():
    logging_common.log.info('Pushing stats messages to all')
    docs_count = data_provider.get_docs_count_from_yesterday()

    message = 'We got {:d} new documents from yesterday!'.format(docs_count)
    data_provider.push_message_to_all(message)

    logging_common.log.info('Success!')


if __name__ == '__main__':
    main()
