#!/usr/bin/env python
import data_provider


def main():
    docs_count = data_provider.get_docs_count_from_yesterday()

    message = 'We got {:d} new documents till yesterday!'.format(docs_count)
    data_provider.push_message_to_all(message)

    print 'Success!'

if __name__ == '__main__':
    main()
