#!/usr/bin/env python
import logging
import data_provider


def main():
    logging.info('Pushing stats messages to all')
    docs_count = data_provider.get_docs_count_from_yesterday()

    message = 'We got {:d} new documents from yesterday!'.format(docs_count)
    data_provider.push_message_to_all(message)

    logging.info('Success!')

if __name__ == '__main__':
    main()
