#!/usr/bin/env bash

set -ex

CUR_DIR="$(cd "$(dirname "$0")" && pwd)"
cd "$CUR_DIR"

if [[ -z "$(docker ps | grep scrapper_api_testing_web)" ]]; then
    .testing/start-service
fi

source .testing/environment

pyresttest "http://127.0.0.1:$WEB_PORT" endpoint-specs.yml

if [[ $1 != '--no-stop-service' ]]; then
    .testing/stop-service
fi
