#!/usr/bin/env bash

set -ex

cd "$(dirname "$0")"

pytest


if [[ -z "$(docker ps | grep scrapper_api_testing_web)" ]]; then
    .testing/start-service
fi

source .testing/environment

set +e
pyresttest "http://127.0.0.1:$WEB_PORT" endpoint-specs.yml
result=$?
set -e

if [[ $1 != '--no-stop-service' ]]; then
    .testing/stop-service
fi

exit "$result"
